<?php
return array (
  'DB_TYPE' => 'mysql',
  'DB_HOST' => '127.0.0.1',
  'DB_NAME' => 'ites',
  'DB_USER' => 'root',
  'DB_PWD' => '111111',
  'DB_PORT' => 3306,
  'DB_PREFIX' => 'it_',
  'APP_DEBUG' => 1,
  'SHOW_ERROR_MSG' => 1,
  'SHOW_PAGE_TRACE' => 1,
  'DATA_CACHE_TYPE' => 'Redis',
  'REDIS_HOST' => '127.0.0.1',
  'REDIS_PORT' => 6379,
  'DATA_CACHE_TIME' => 3600,
  'URL_CASE_INSENSITIVE' => true,
  'TMPL_STRIP_SPACE' => false,
  'URL_HTML_SUFFIX' => '',
  'SITE_NAME' => '11111',
  'SITE_URL' => 'http://www.aaaaaaaaaaaa.com/',
  'WECHAT_TOKEN' => 'ÄãµÄ',
  'WECHAT_APPID' => 'ÄãµÄ',
  'WECHAT_APPSECRET' => 'ÄãµÄ',
  'DATA_AUTH_KEY' => 'abcdddd',
);
?>